// Generated by gencpp from file final_project/iksolver.msg
// DO NOT EDIT!


#ifndef FINAL_PROJECT_MESSAGE_IKSOLVER_H
#define FINAL_PROJECT_MESSAGE_IKSOLVER_H

#include <ros/service_traits.h>


#include <final_project/iksolverRequest.h>
#include <final_project/iksolverResponse.h>


namespace final_project
{

struct iksolver
{

typedef iksolverRequest Request;
typedef iksolverResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct iksolver
} // namespace final_project


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::final_project::iksolver > {
  static const char* value()
  {
    return "c531b06618eadc33dc6f14fc3026e8e5";
  }

  static const char* value(const ::final_project::iksolver&) { return value(); }
};

template<>
struct DataType< ::final_project::iksolver > {
  static const char* value()
  {
    return "final_project/iksolver";
  }

  static const char* value(const ::final_project::iksolver&) { return value(); }
};


// service_traits::MD5Sum< ::final_project::iksolverRequest> should match
// service_traits::MD5Sum< ::final_project::iksolver >
template<>
struct MD5Sum< ::final_project::iksolverRequest>
{
  static const char* value()
  {
    return MD5Sum< ::final_project::iksolver >::value();
  }
  static const char* value(const ::final_project::iksolverRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::final_project::iksolverRequest> should match
// service_traits::DataType< ::final_project::iksolver >
template<>
struct DataType< ::final_project::iksolverRequest>
{
  static const char* value()
  {
    return DataType< ::final_project::iksolver >::value();
  }
  static const char* value(const ::final_project::iksolverRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::final_project::iksolverResponse> should match
// service_traits::MD5Sum< ::final_project::iksolver >
template<>
struct MD5Sum< ::final_project::iksolverResponse>
{
  static const char* value()
  {
    return MD5Sum< ::final_project::iksolver >::value();
  }
  static const char* value(const ::final_project::iksolverResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::final_project::iksolverResponse> should match
// service_traits::DataType< ::final_project::iksolver >
template<>
struct DataType< ::final_project::iksolverResponse>
{
  static const char* value()
  {
    return DataType< ::final_project::iksolver >::value();
  }
  static const char* value(const ::final_project::iksolverResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FINAL_PROJECT_MESSAGE_IKSOLVER_H
