<?xml version="1.0"?>
<!-- Revolute-Revolute-Prismatic Manipulator -->
<robot name="rrpbot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Constants for robot dimensions -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="mass" value="1" /> 
  <xacro:property name="width" value="0.1" /> <!-- Square sizes -->
  <xacro:property name="height1" value="0.5" /> <!-- Link 1 -->
  <xacro:property name="height2" value="0.5" /> <!-- Link 2 -->
  <xacro:property name="height3" value="0.5" /> <!-- Link 3 -->
  <xacro:property name="height4" value="0.5" /> <!-- Link 4 -->
  <xacro:property name="axel_offset" value="0.05" /> <!-- Space between top of link and each joint -->

  <xacro:include filename="$(find final_project)/urdf/rrpbot.gazebo" />
  <xacro:include filename="$(find final_project)/urdf/materials.xacro" /> 
 
  <!-- fix base_frame to world  -->
  <link name="world"/>

  <joint name="joint0" type="fixed">
    <parent link="world"/>
    <child link="link1"/>
  </joint>

  <!-- Base Link -->
  <link name="link1">
    <collision>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height1}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height1}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (width*width + height1*height1)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (height1*height1 + width*width)}" iyz="0.0"
	  izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>
  </link>

  <joint name="joint1" type="continuous">
    <parent link="link1"/>
    <child link="link2"/>
    <origin xyz="0 0 ${height1 + axel_offset}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.7"/>
  </joint>

  <!-- Middle Link 1-->
  <link name="link2">
    <collision>
      <origin xyz="${height2/2 - axel_offset} 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="${height2} ${width} ${width}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="${height2/2 - axel_offset} 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="${height2} ${width} ${width}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="${height2/2 - axel_offset} 0 0" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (width*width + height2*height2)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (height2*height2 + width*width)}" iyz="0.0"
	  izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>
  </link>
  
  <joint name="joint2" type="continuous">
    <parent link="link2"/>
    <child link="link3"/>
    <origin xyz="${height2 - width} 0 ${width}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.7"/>
  </joint>
  
  <!-- Middle Link 2-->
  <link name="link3">
    <collision>
      <origin xyz="${height3/2 - axel_offset} 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="${height3} ${width} ${width} "/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="${height3/2 - axel_offset} 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="${height3} ${width} ${width} "/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="${height3/2 - axel_offset} 0 0" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (width*width + height3*height3)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (height3*height3 + width*width)}" iyz="0.0"
	  izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>
  </link>
  
  <joint name="joint3" type="prismatic">
    <parent link="link3"/>
    <child link="link4"/>
    <origin xyz="${height4} 0 0" rpy="${PI} 0 0"/>
    <limit effort="1000.0" lower="-0.25" upper="0.25" velocity="0.5"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.7"/>
  </joint>
  
  <!-- End effector -->
  <link name="link4">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height4}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height4}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (width*width + height3*height3)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (height3*height3 + width*width)}" iyz="0.0"
	  izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>
  </link>
  <transmission name="rot1_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint1">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor1">
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  <transmission name="rot2_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint2">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor2">
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  <transmission name="lin1_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint3">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="piston1">
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <gazebo>
   <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
    <robotNamespace>/</robotNamespace>
   </plugin>
  </gazebo>
</robot>
